# Generated by Django 6.0.2 on 2026-08-26 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('event_date', models.CharField(blank=True, max_length=100)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Client Inquiry',
                'verbose_name_plural': 'Client Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='Bachelor of Hospital Administration (BHA)', max_length=250)),
                ('institution', models.CharField(default='Yenepoya School of Allied Health Sciences, Mangalore', max_length=250)),
                ('period', models.CharField(default='2023 – 2026', max_length=100)),
                ('description', models.TextField(blank=True, default='Comprehensive management, communication, and operational leadership training.')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(default='Bengaluru, India', max_length=150)),
                ('duration', models.CharField(help_text='e.g. 2022 – Present or August 2025 – September 2025', max_length=100)),
                ('duration_length', models.CharField(blank=True, help_text='e.g. 1 Month or 3+ Years', max_length=100)),
                ('achievement', models.CharField(blank=True, max_length=300)),
                ('responsibilities', models.TextField(help_text='Enter key points separated by newlines')),
                ('is_current', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('wedding', 'Wedding Photography'), ('events', 'Events'), ('portraits', 'Portraits'), ('commercial', 'Commercial')], default='wedding', max_length=30)),
                ('location', models.CharField(blank=True, default='Bengaluru, India', max_length=150)),
                ('year', models.CharField(blank=True, default='2025', max_length=10)),
                ('camera_spec', models.CharField(blank=True, default='Sony Cinema / 50mm T1.4', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('aspect_type', models.CharField(choices=[('portrait', 'Portrait Tall (4:5)'), ('landscape', 'Landscape Wide (16:9)'), ('square', 'Square (1:1)')], default='landscape', max_length=30)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Photography / Still Item',
                'verbose_name_plural': 'Photography / Still Gallery',
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Mohamed Ashiq CM', max_length=150)),
                ('brand_name', models.CharField(default='ASKY', max_length=100)),
                ('professional_title', models.CharField(default='Videographer & Video Editor', max_length=200)),
                ('short_bio', models.TextField(default='Videographer and Video Editor with hands-on experience in wedding videography, content creation, and video post-production. Skilled in directing video shoots, managing on-site production teams, and coordinating with clients from concept to final delivery. Experienced in social media content creation, event coordination, and team communication.')),
                ('hero_headline', models.CharField(default='Capturing The Poetry of Light & Cinematic Stories', max_length=200)),
                ('hero_subheadline', models.TextField(default='Specializing in emotive wedding films, dynamic social content, and precision post-production edited with DaVinci Resolve & Premiere Pro.')),
                ('location', models.CharField(default='Bengaluru, India', max_length=150)),
                ('phone', models.CharField(default='9061733155', max_length=30)),
                ('email', models.EmailField(default='ashiqchangal@gmail.com', max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, default='919061733155', max_length=30)),
                ('instagram_handle', models.CharField(default='@askie._', max_length=100)),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/askie._')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('experience_start_year', models.IntegerField(default=2022)),
                ('wedding_films_delivered', models.IntegerField(default=50)),
                ('client_satisfaction_rate', models.IntegerField(default=99)),
                ('awards_count', models.IntegerField(default=5)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('profile_photo_url', models.URLField(blank=True, default='')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personal Profile',
                'verbose_name_plural': 'Personal Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(choices=[('WEDDING', 'Wedding Film & Highlights'), ('CINEMATIC', 'Cinematic Film'), ('EVENT', 'Event Videography'), ('COMMERCIAL', 'Commercial & Brand'), ('REEL', 'Social Media Reel')], default='WEDDING', max_length=30)),
                ('year', models.CharField(default='2025', max_length=10)),
                ('location', models.CharField(default='Bengaluru, India', max_length=150)),
                ('client', models.CharField(blank=True, max_length=150)),
                ('focal_length', models.CharField(blank=True, default='35mm & 50mm Prime', max_length=100)),
                ('aspect_ratio', models.CharField(blank=True, default='2.39:1 CinemaScope', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='', help_text='Direct MP4 URL or YouTube/Vimeo link')),
                ('overview', models.TextField(blank=True)),
                ('awards', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Featured Project',
                'verbose_name_plural': 'Featured Projects',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('VIDEOGRAPHY', 'Videography'), ('PRODUCTION', 'Video Production'), ('POST_PRODUCTION', 'Post-Production')], default='VIDEOGRAPHY', max_length=30)),
                ('icon', models.CharField(default='film', help_text='e.g. film, camera, video, edit, aperture, zap', max_length=50)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Features separated by newlines')),
                ('badge_label', models.CharField(blank=True, default='', max_length=50)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Offering',
                'verbose_name_plural': 'Service Offerings',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SOFTWARE', 'Software & Post-Production'), ('VIDEOGRAPHY', 'Videography & Cinematography'), ('PRODUCTION', 'Production & Directing'), ('MANAGEMENT', 'Management & Communication')], default='VIDEOGRAPHY', max_length=30)),
                ('proficiency_percent', models.IntegerField(default=90)),
                ('badge_color', models.CharField(blank=True, default='gold', max_length=30)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill & Expertise',
                'verbose_name_plural': 'Skills & Expertise',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_role', models.CharField(default='Wedding Client', max_length=150)),
                ('project_title', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Client Testimonial',
                'verbose_name_plural': 'Client Testimonials',
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VideoReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Wedding Cinema', max_length=100)),
                ('duration', models.CharField(default='01:30', max_length=30)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('video_url', models.URLField(help_text='Direct MP4 URL, YouTube, or Vimeo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_reels/')),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('aspect_ratio', models.CharField(blank=True, default='16:9 Cinema', max_length=30)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Video Reel',
                'verbose_name_plural': 'Video Reels',
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_gallery/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.project')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
