# Generated by Django 6.0.2 on 2026-09-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4, WebM, or MOV video file', null=True, upload_to='videos/projects/'),
        ),
        migrations.AddField(
            model_name='videoreel',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4, WebM, or MOV video file directly from your computer', null=True, upload_to='videos/reels/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Or direct MP4 URL, YouTube, or Vimeo link'),
        ),
        migrations.AlterField(
            model_name='videoreel',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Or direct MP4 URL, YouTube, or Vimeo link'),
        ),
    ]
