# Generated by Django 6.0.2 on 2026-09-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_video_file_videoreel_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Custom Hero section artwork / main display image', null=True, upload_to='profile/hero/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_image_url',
            field=models.URLField(blank=True, default='', help_text='Or external URL for hero image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='About section portrait photo', null=True, upload_to='profile/'),
        ),
    ]
