# Generated by Django 6.0.2 on 2026-09-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_hero_image_profile_hero_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload client avatar photo', null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('wedding', 'Wedding Photography'), ('events', 'Events'), ('portraits', 'Portraits'), ('cinematic', 'Cinematic & Films'), ('commercial', 'Commercial')], default='wedding', max_length=30),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload photo or still frame', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='videoreel',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload custom thumbnail / poster image', null=True, upload_to='video_reels/'),
        ),
    ]
